// ===========================================================================
// AUTO-GENERATED BY NPU COMPILE PASS (TRUE OOP POLYMORPHISM)
// ===========================================================================
#include "npu_api.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>

int32_t bias_l1[8];
int32_t bias_l2[128];
int32_t bias_l3[16];
int32_t labels[10000];

void npu_auto_inference(int num_batches, double *time_ms, double *accuracy) {
    int correct_predictions = 0;
    struct timeval tv; gettimeofday(&tv, NULL);
    double start_time = (double)tv.tv_sec * 1000000.0 + (double)tv.tv_usec;
    int8_t *l1_drain_buf = (int8_t*)(virt_ddr_base + 0x900000); // Scratchpad Ping
    int8_t *H_flat = (int8_t*)(virt_ddr_base + 0x920000); // 1MB Global Flat Bridge Tensor

    for (int b = 0; b < num_batches; b++) {
        if (b % 100 == 0) printf("    [EmitC] Processing Sequence %d...\n", b);

        // -------- Layer 1 [Conv2D]: conv1 --------
        int8_t* X_hw = (int8_t*)(virt_ddr_base + 0x900000);
        memset(X_hw, 0, ((676 + 7)/8) * 2 * 64);
        uint8_t* img_src = (uint8_t*)(virt_ddr_base + 0x000000 + b * 28 * 28);
        // Software Im2Col HW-Aligned Padding & Unrolling
        int patch_idx = 0;
        for(int py = 0; py < 26; py++) {
            for(int px = 0; px < 26; px++) {
                int feature_idx = 0;
                for(int c_in = 0; c_in < 1; c_in++) {
                    for(int ky = 0; ky < 3; ky++) {
                        for(int kx = 0; kx < 3; kx++) {
                            int orig_y = (py * 1) - 0 + ky;
                            int orig_x = (px * 1) - 0 + kx;
                            int8_t pval = 0;
                            if (orig_y >= 0 && orig_y < 28 && orig_x >=0 && orig_x < 28) {
                                pval = (int8_t)img_src[c_in * 784 + orig_y * 28 + orig_x];
                            }
                            int p_tile = patch_idx / 8; int p_rem = patch_idx % 8;
                            int f_tile = feature_idx / 8; int f_rem = feature_idx % 8;
                            int mem_offset = (p_tile * 2 + f_tile) * 64 + (p_rem * 8 + f_rem);
                            X_hw[mem_offset] = pval;
                            feature_idx++;
                        }
                    }
                }
                patch_idx++;
            }
        }

        int out_patches_tiles = (676 + 7) / 8;
        int8_t* Y_img_out = (int8_t*)(virt_ddr_base + 0x820000); // Temporary Spatial Output
        memset(Y_img_out, 0, 8 * 676);
        for (int p_t = 0; p_t < out_patches_tiles; p_t++) {
            for (int j = 0; j < 1; j++) {
                npu_clear_ocm(); npu_set_seq_rows(8);
                for (int t = 0; t < 2; t++) {
                    npu_load_weights(0x800000 + (t * 1 + j) * 64);
                    npu_accum_start();
                    npu_load_inputs(0x900000 + (p_t * 2 + t) * 64);
                    npu_wait_accum();
                }
                npu_set_shift(8);
                npu_load_bias(&bias_l1[j * 8]);
                npu_drain_to_ddr(0x910000);
                for(int r=0; r<8; r++) {
                    int absolute_patch = p_t * 8 + r; if (absolute_patch >= 676) continue;
                    for(int c=0; c<8; c++) {
                        int absolute_channel = j * 8 + c; if (absolute_channel >= 8) continue;
                        int8_t clamped = ((int8_t*)(virt_ddr_base + 0x910000))[r * 8 + (7 - c)];
                        Y_img_out[absolute_channel * 676 + absolute_patch] = clamped;
                    }
                }
            }
        }

        // MaxPool2D execution (CPU Reference Fallback)
        for(int c_out=0; c_out<8; c_out++) {
            for(int py=0; py<13; py++) {
                for(int px=0; px<13; px++) {
                    int8_t max_v = -128;
                    for(int ky=0; ky<2; ky++) {
                        for(int kx=0; kx<2; kx++) {
                            int orig_y = py*2 + ky; int orig_x = px*2 + kx;
                            int8_t v = Y_img_out[c_out*676 + orig_y*26 + orig_x];
                            if (v > max_v) max_v = v;
                        }
                    }
                    H_flat[c_out*169 + py*13 + px] = max_v;
                }
            }
        }

        // -------- Layer 2 [Linear]: fc1 --------
        for (int j = 0; j < 16; j++) {
            npu_clear_ocm(); npu_set_seq_rows(8);
            for (int t = 0; t < 169; t++) {
                uint8_t *h_ptr = virt_ddr_base + 0x904000;
                for(int r = 0; r < 8; r++) {
                    uint32_t low = 0, high = 0;
                    for(int c_i=0; c_i<4; c_i++) {
                        int8_t v0 = (r == 0 && (t*8+c_i) < 1352) ? H_flat[t*8+c_i] : 0;
                        int8_t v1 = (r == 0 && (t*8+c_i+4) < 1352) ? H_flat[t*8+c_i+4] : 0;
                        low |= (((uint32_t)(uint8_t)v0) << (c_i*8));
                        high |= (((uint32_t)(uint8_t)v1) << (c_i*8));
                    }
                    ((volatile uint32_t*)h_ptr)[r*2+0] = low; ((volatile uint32_t*)h_ptr)[r*2+1] = high;
                }
                volatile uint32_t dummy = ((volatile uint32_t*)h_ptr)[0]; (void)dummy;
                uint32_t curr_x_off = 0x904000;
                npu_load_weights(0x810000 + (t * 16 + j) * 64);
                npu_accum_start();
                npu_load_inputs(curr_x_off);
                npu_wait_accum();
            }
            npu_set_shift(8);
            npu_load_bias(&bias_l2[j * 8]);
            npu_drain_to_ddr(0x910000);
            for(int r=0; r<8; r++) { for(int c_i=0; c_i<8; c_i++) {
                int8_t clamped = ((int8_t*)(virt_ddr_base + 0x910000))[r * 8 + (7 - c_i)];
                if (r==0) ((int8_t*)(virt_ddr_base + 0x930000))[j*8+c_i] = clamped;
            } }
        }

        memcpy(H_flat, (int8_t*)(virt_ddr_base + 0x930000), 128);

        // -------- Layer 3 [Linear]: fc2 --------
        for (int j = 0; j < 2; j++) {
            npu_clear_ocm(); npu_set_seq_rows(8);
            for (int t = 0; t < 16; t++) {
                uint8_t *h_ptr = virt_ddr_base + 0x904000;
                for(int r = 0; r < 8; r++) {
                    uint32_t low = 0, high = 0;
                    for(int c_i=0; c_i<4; c_i++) {
                        int8_t v0 = (r == 0 && (t*8+c_i) < 128) ? H_flat[t*8+c_i] : 0;
                        int8_t v1 = (r == 0 && (t*8+c_i+4) < 128) ? H_flat[t*8+c_i+4] : 0;
                        low |= (((uint32_t)(uint8_t)v0) << (c_i*8));
                        high |= (((uint32_t)(uint8_t)v1) << (c_i*8));
                    }
                    ((volatile uint32_t*)h_ptr)[r*2+0] = low; ((volatile uint32_t*)h_ptr)[r*2+1] = high;
                }
                volatile uint32_t dummy = ((volatile uint32_t*)h_ptr)[0]; (void)dummy;
                uint32_t curr_x_off = 0x904000;
                npu_load_weights(0x840000 + (t * 2 + j) * 64);
                npu_accum_start();
                npu_load_inputs(curr_x_off);
                npu_wait_accum();
            }
            int32_t z_b[64] = {0};
            npu_extract_32bit_ocm(z_b, &bias_l3[j * 8]);
            for(int r=0; r<8; r++) { for(int c_i=0; c_i<8; c_i++) { ((int32_t*)virt_ddr_base)[0x910000/4 + (r*16) + (j*8+c_i)] = z_b[r*8+c_i]; } }
        }

        int32_t* Y_final = (int32_t*)(virt_ddr_base + 0x910000);
        int best_class = 0; int32_t max_val = Y_final[0];
        for (int k = 1; k < 10; k++) { if (Y_final[k] > max_val) { max_val = Y_final[k]; best_class = k; } }
        if (best_class == labels[b]) correct_predictions++;
    }

    gettimeofday(&tv, NULL);
    double e_t = (double)tv.tv_sec * 1000000.0 + (double)tv.tv_usec;
    *time_ms = (e_t - start_time) / 1000.0;
    *accuracy = (double)correct_predictions / num_batches * 100.0;
}

int main(int argc, char **argv) {
    int num_test_batches = 100;
    if (argc > 1) { num_test_batches = atoi(argv[1]); }
    printf("=== Auto-Generated EmitC OOP Benchmark ===\n");
    if (npu_init() < 0) return -1;
    printf("\nLoading Binaries...\n");
    npu_load_binary_file("inputs.bin", virt_ddr_base + 0x000000, 8000000);
    npu_load_binary_file("weights_l1.bin", virt_ddr_base + 0x800000, 200000);
    npu_load_binary_file("bias_l1.bin", bias_l1, 256);
    npu_load_binary_file("weights_l2.bin", virt_ddr_base + 0x810000, 200000);
    npu_load_binary_file("bias_l2.bin", bias_l2, 256);
    npu_load_binary_file("weights_l3.bin", virt_ddr_base + 0x840000, 200000);
    npu_load_binary_file("bias_l3.bin", bias_l3, 256);
    npu_load_binary_file("labels.bin", labels, 40000);
    double time_ms, acc;
    npu_auto_inference(num_test_batches, &time_ms, &acc);
    printf("    EmitC Accuracy : %.2f%%\n", acc);
    printf("    EmitC Time     : %.2f ms (%.3f ms/img)\n", time_ms, time_ms / num_test_batches);
    npu_close(); return 0;
}
