// ===========================================================================
// AUTO-GENERATED BY NPU COMPILE PASS
// PyTorch FX -> Embedded C Transpiler (Emit C)
// ===========================================================================
#include "npu_api.h"
#include <stdio.h>
#include <stdint.h>

void run_npu_inference(int8_t* system_input_ptr, int8_t* system_output_ptr) {
    printf("[NPU Runtime] Starting FPGA Hardware Execution...\n");

    // --- Model Input: x ---
    // --- Hardware Matrix Fusion execution for npu_conv1 ---
    int8_t* intermediate_buf_0 = allocate_npu_buffer(MAX_LAYER_SIZE);
    npu_load_weights("npu_conv1_weights.bin");
    npu_load_bias("npu_conv1_bias.bin");
    npu_set_shift(8);
    npu_execute_dma(system_input_ptr, intermediate_buf_0, 8, 3);

    // --- CPU Fallback execution for Fully Connected: fc ---
    int8_t* intermediate_buf_1 = allocate_npu_buffer(MAX_LAYER_SIZE);
    cpu_execute_fc(intermediate_buf_0, "fc_weights.bin", "fc_bias.bin", intermediate_buf_1);

    // --- Output Transfer ---
    copy_to_system_output(intermediate_buf_1, system_output_ptr);
    printf("[NPU Runtime] Graph Execution Completed.\n");
}
