// ===========================================================================
// AUTO-GENERATED BY NPU COMPILE PASS (TRUE OOP POLYMORPHISM)
// ===========================================================================
#include "npu_api.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>

int32_t bias_l1[64];
int32_t bias_l2[16];
int32_t labels[10000];

void npu_auto_inference(int num_batches, double *time_ms, double *accuracy) {
    int correct_predictions = 0;
    struct timeval tv; gettimeofday(&tv, NULL);
    double start_time = (double)tv.tv_sec * 1000000.0 + (double)tv.tv_usec;
    int8_t *l1_drain_buf = (int8_t*)(virt_ddr_base + 0x900000); // Scratchpad Ping
    int8_t *H_flat = (int8_t*)(virt_ddr_base + 0x920000); // 1MB Global Flat Bridge Tensor

    for (int b = 0; b < num_batches; b++) {
        if (b % 100 == 0) printf("    [EmitC] Processing Sequence %d...\n", b);

        // -------- Layer 1 [Linear]: fc1 --------
        for (int j = 0; j < 8; j++) {
            npu_clear_ocm(); npu_set_seq_rows(8);
            for (int t = 0; t < 98; t++) {
                uint32_t curr_x_off = 0x000000 + (b * 98 + t) * 64;
                npu_load_weights(0x800000 + (t * 8 + j) * 64);
                npu_accum_start();
                npu_load_inputs(curr_x_off);
                npu_wait_accum();
            }
            npu_set_shift(8);
            npu_load_bias(&bias_l1[j * 8]);
            npu_drain_to_ddr(0x910000);
            for(int r=0; r<8; r++) { for(int c_i=0; c_i<8; c_i++) {
                int8_t clamped = ((int8_t*)(virt_ddr_base + 0x910000))[r * 8 + (7 - c_i)];
                ((int8_t*)(virt_ddr_base + 0x930000))[r * 64 + (j*8+c_i)] = clamped;
            } }
        }

        memcpy(H_flat, (int8_t*)(virt_ddr_base + 0x930000), 512);

        // -------- Layer 2 [Linear]: fc2 --------
        for (int j = 0; j < 2; j++) {
            npu_clear_ocm(); npu_set_seq_rows(8);
            for (int t = 0; t < 8; t++) {
                uint8_t *h_ptr = virt_ddr_base + 0x904000;
                for(int r = 0; r < 8; r++) {
                    uint32_t low = 0, high = 0;
                    for(int c_i=0; c_i<4; c_i++) {
                        low |= (((uint32_t)(uint8_t)H_flat[r * 64 + t*8+c_i]) << (c_i*8));
                        high |= (((uint32_t)(uint8_t)H_flat[r * 64 + t*8+c_i+4]) << (c_i*8));
                    }
                    ((volatile uint32_t*)h_ptr)[r*2+0] = low; ((volatile uint32_t*)h_ptr)[r*2+1] = high;
                }
                volatile uint32_t dummy = ((volatile uint32_t*)h_ptr)[0]; (void)dummy;
                uint32_t curr_x_off = 0x904000;
                npu_load_weights(0x810000 + (t * 2 + j) * 64);
                npu_accum_start();
                npu_load_inputs(curr_x_off);
                npu_wait_accum();
            }
            int32_t z_b[64] = {0};
            npu_extract_32bit_ocm(z_b, &bias_l2[j * 8]);
            for(int r=0; r<8; r++) { for(int c_i=0; c_i<8; c_i++) { ((int32_t*)virt_ddr_base)[0x910000/4 + (r*16) + (j*8+c_i)] = z_b[r*8+c_i]; } }
        }

        int32_t* Y_final = (int32_t*)(virt_ddr_base + 0x910000);
        for (int r = 0; r < 8; r++) {
            int best_class = 0; int32_t max_val = Y_final[r*16 + 0];
            for (int k = 1; k < 10; k++) { if (Y_final[r*16 + k] > max_val) { max_val = Y_final[r*16 + k]; best_class = k; } }
            if (best_class == labels[b * 8 + r]) correct_predictions++;
        }
    }

    gettimeofday(&tv, NULL);
    double e_t = (double)tv.tv_sec * 1000000.0 + (double)tv.tv_usec;
    *time_ms = (e_t - start_time) / 1000.0;
    *accuracy = (double)correct_predictions / (num_batches * 8) * 100.0;
}

int main(int argc, char **argv) {
    int num_test_batches = 125;
    if (argc > 1) { num_test_batches = atoi(argv[1]) / 8; }
    printf("=== Auto-Generated EmitC OOP Benchmark ===\n");
    if (npu_init() < 0) return -1;
    printf("\nLoading Binaries...\n");
    npu_load_binary_file("inputs.bin", virt_ddr_base + 0x000000, 8000000);
    npu_load_binary_file("weights_l1.bin", virt_ddr_base + 0x800000, 2000000);
    npu_load_binary_file("bias_l1.bin", bias_l1, 4096);
    npu_load_binary_file("weights_l2.bin", virt_ddr_base + 0x810000, 2000000);
    npu_load_binary_file("bias_l2.bin", bias_l2, 4096);
    npu_load_binary_file("labels.bin", labels, 40000);
    double time_ms, acc;
    npu_auto_inference(num_test_batches, &time_ms, &acc);
    printf("    EmitC Accuracy : %.2f%%\n", acc);
    printf("    EmitC Time     : %.2f ms (%.3f ms/img)\n", time_ms, time_ms / (num_test_batches * 8));
    npu_close(); return 0;
}
