// ===========================================================================
// AUTO-GENERATED BY NPU COMPILE PASS (EmitC)
// Target: Terasic DE10-Nano (Cyclone V HPS + MSGDMA 8x8 Systolic Array)
// ===========================================================================

#include "npu_api.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>

int32_t bias_l1[64];
int32_t bias_l2[16];
int32_t labels[10000];

void npu_auto_inference(int num_batches, double *time_ms, double *accuracy) {
    int correct_predictions = 0;
    struct timeval tv;
    gettimeofday(&tv, NULL);
    double start_time = (double)tv.tv_sec * 1000000.0 + (double)tv.tv_usec;

    int8_t *l1_drain_buf = (int8_t*)(virt_ddr_base + 0x900000);

    for (int b = 0; b < num_batches; b++) {
        if (b % 100 == 0) printf("    [EmitC] Processing Batch %d...\n", b);
        int8_t H[8][64]; memset(H, 0, sizeof(H));

        // ---------------- Layer 1: fc1 ----------------
        // Geometry -> Inputs: 784, Outputs: 64
        for (int j = 0; j < 8; j++) {
            npu_clear_ocm();
            npu_set_seq_rows(8);
            for (int t = 0; t < 98; t++) {
                uint32_t curr_w_off = 0x800000 + (t * 8 + j) * 64;
                uint32_t curr_x_off = 0x000000 + (b * 98 + t) * 64;
                npu_load_weights(curr_w_off);
                npu_accum_start();
                npu_load_inputs(curr_x_off);
                npu_wait_accum();
            }
            npu_load_bias(&bias_l1[j * 8]);
            npu_drain_to_ddr(0x900000);
            for(int r=0; r<8; r++) { for(int c=0; c<8; c++) { H[r][j*8+c] = l1_drain_buf[r*8+(7-c)]; } }
        }

        // ---------------- Layer 2: fc2 ----------------
        // Geometry -> Inputs: 64, Outputs: 16
        for (int j = 0; j < 2; j++) {
            npu_clear_ocm();
            npu_set_seq_rows(8);
            for (int t = 0; t < 8; t++) {
                uint32_t curr_w_off = 0x810000 + (t * 2 + j) * 64;
                uint8_t *h_ptr = virt_ddr_base + 0x901000;
                for(int r = 0; r < 8; r++) {
                    uint32_t low = 0, high = 0;
                    for(int c=0; c<4; c++) {
                        low |= (((uint32_t)(uint8_t)H[r][t*8+c]) << (c*8));
                        high |= (((uint32_t)(uint8_t)H[r][t*8+c+4]) << (c*8));
                    }
                    ((volatile uint32_t*)h_ptr)[r*2+0] = low;
                    ((volatile uint32_t*)h_ptr)[r*2+1] = high;
                }
                volatile uint32_t ddr_dummy = ((volatile uint32_t*)h_ptr)[0]; (void)ddr_dummy;
                uint32_t curr_x_off = 0x901000;
                npu_load_weights(curr_w_off);
                npu_accum_start();
                npu_load_inputs(curr_x_off);
                npu_wait_accum();
            }
            int32_t host_z_buf[64] = {0};
            npu_extract_32bit_ocm(host_z_buf, &bias_l2[j * 8]);
            for(int r=0; r<8; r++) { for(int c=0; c<8; c++) { ((int32_t*)virt_ddr_base)[0x910000/4 + (r*16) + (j*8+c)] = host_z_buf[r*8+c]; } }
        }

        // Standard Evaluation (CPU ArgMax)
        int32_t* Y_final = (int32_t*)(virt_ddr_base + 0x910000);
        for (int r = 0; r < 8; r++) {
            int best_class = 0; int32_t max_val = Y_final[r*16 + 0];
            for (int k = 1; k < 10; k++) {
                if (Y_final[r*16 + k] > max_val) { max_val = Y_final[r*16 + k]; best_class = k; }
            }
            if (best_class == labels[b * 8 + r]) correct_predictions++;
        }
    }

    gettimeofday(&tv, NULL);
    double end_time = (double)tv.tv_sec * 1000000.0 + (double)tv.tv_usec;
    *time_ms = (end_time - start_time) / 1000.0;
    *accuracy = (double)correct_predictions / (num_batches * 8) * 100.0;
}

int main(int argc, char **argv) {
    int num_test_batches = 125;
    if (argc > 1) { num_test_batches = atoi(argv[1]) / 8; }
    printf("=== Auto-Generated EmitC NPU Benchmark ===\n");
    if (npu_init() < 0) return -1;
    printf("\nLoading Binaries...\n");
    npu_load_binary_file("inputs.bin", virt_ddr_base + 0x000000, 8000000);
    npu_load_binary_file("weights_l1.bin", virt_ddr_base + 0x800000, 200000);
    npu_load_binary_file("bias_l1.bin", bias_l1, 256);
    npu_load_binary_file("weights_l2.bin", virt_ddr_base + 0x810000, 200000);
    npu_load_binary_file("bias_l2.bin", bias_l2, 256);
    npu_load_binary_file("labels.bin", labels, 40000);
    double time_ms, acc;
    npu_auto_inference(num_test_batches, &time_ms, &acc);
    printf("    EmitC Accuracy : %.2f%%\n", acc);
    printf("    EmitC Time     : %.2f ms (%.3f ms/img)\n", time_ms, time_ms / (num_test_batches * 8));
    npu_close();
    return 0;
}
