import os

class NPUCompiler:
    """
    Bring-Your-Own-Compiler (BYOC) Auto-Codegen Backend for Cyclone V Systolic Arrays.
    Dynamically emits a bare-metal Linux C driver directly mimicking PyTorch Graph topology.
    """
    def __init__(self, out_c_file="npu_model_runtime.c"):
        self.code = []
        self.out_c_file = out_c_file
        
        # DDR Memory Allocation Map (NPU View)
        self.mem_inputs = 0x000000
        self.mem_weights = 0x800000
        self.mem_intermediate = 0x900000
        
        self.layer_meta = []
        
    def allocate_weights(self, num_bytes):
        # 64KB Alignments for safety across MSGDMA boundaries
        addr = self.mem_weights
        self.mem_weights += num_bytes
        self.mem_weights = (self.mem_weights + 0xFFFF) & ~0xFFFF
        return addr
        
    def register_linear_fused_layer(self, name, in_features, out_features, has_relu):
        in_tiles = in_features // 8 + (1 if in_features % 8 else 0)
        out_tiles = out_features // 8 + (1 if out_features % 8 else 0)
        
        w_addr = self.allocate_weights(in_tiles * out_tiles * 64)
        
        layer = {
            "name": name,
            "in_tiles": in_tiles,
            "out_tiles": out_tiles,
            "weight_addr": w_addr,
            "has_relu": has_relu
        }
        self.layer_meta.append(layer)
        return layer

    def generate_c_code(self):
        c = []
        c.append("// ===========================================================================")
        c.append("// AUTO-GENERATED BY NPU COMPILE PASS (EmitC)")
        c.append("// Target: Terasic DE10-Nano (Cyclone V HPS + MSGDMA 8x8 Systolic Array)")
        c.append("// ===========================================================================")
        c.append("")
        c.append("#include \"npu_api.h\"")
        c.append("#include <stdio.h>")
        c.append("#include <stdlib.h>")
        c.append("#include <string.h>")
        c.append("#include <sys/time.h>")
        c.append("")
        
        # User environment arrays required by the manual validation wrapper
        c.append("int32_t bias_l1[64];")
        c.append("int32_t bias_l2[16];")
        c.append("int32_t labels[10000];")
        c.append("")
        
        c.append("void npu_auto_inference(int num_batches, double *time_ms, double *accuracy) {")
        c.append("    int correct_predictions = 0;")
        c.append("    struct timeval tv;")
        c.append("    gettimeofday(&tv, NULL);")
        c.append("    double start_time = (double)tv.tv_sec * 1000000.0 + (double)tv.tv_usec;")
        c.append("")
        c.append("    int8_t *l1_drain_buf = (int8_t*)(virt_ddr_base + 0x900000);")
        c.append("")
        c.append("    for (int b = 0; b < num_batches; b++) {")
        c.append("        if (b % 100 == 0) printf(\"    [EmitC] Processing Batch %d...\\n\", b);")
        c.append("        int8_t H[8][64]; memset(H, 0, sizeof(H));")
        c.append("")
        
        for idx, layer in enumerate(self.layer_meta):
            c.append(f"        // ---------------- Layer {idx+1}: {layer['name']} ----------------")
            c.append(f"        // Geometry -> Inputs: {layer['in_tiles']*8}, Outputs: {layer['out_tiles']*8}")
            c.append(f"        for (int j = 0; j < {layer['out_tiles']}; j++) {{")
            c.append("            npu_clear_ocm();")
            c.append("            npu_set_seq_rows(8);")
            c.append(f"            for (int t = 0; t < {layer['in_tiles']}; t++) {{")
            c.append(f"                uint32_t curr_w_off = 0x{layer['weight_addr']:06X} + (t * {layer['out_tiles']} + j) * 64;")
            
            if idx == 0:
                c.append(f"                uint32_t curr_x_off = 0x000000 + (b * {layer['in_tiles']} + t) * 64;")
            else:
                c.append("                uint8_t *h_ptr = virt_ddr_base + 0x901000;")
                c.append("                for(int r = 0; r < 8; r++) {")
                c.append("                    uint32_t low = 0, high = 0;")
                c.append("                    for(int c=0; c<4; c++) {")
                c.append("                        low |= (((uint32_t)(uint8_t)H[r][t*8+c]) << (c*8));")
                c.append("                        high |= (((uint32_t)(uint8_t)H[r][t*8+c+4]) << (c*8));")
                c.append("                    }")
                c.append("                    ((volatile uint32_t*)h_ptr)[r*2+0] = low;")
                c.append("                    ((volatile uint32_t*)h_ptr)[r*2+1] = high;")
                c.append("                }")
                c.append("                volatile uint32_t ddr_dummy = ((volatile uint32_t*)h_ptr)[0]; (void)ddr_dummy;")
                c.append("                uint32_t curr_x_off = 0x901000;")
                
            c.append("                npu_load_weights(curr_w_off);")
            c.append("                npu_accum_start();")
            c.append("                npu_load_inputs(curr_x_off);")
            c.append("                npu_wait_accum();")
            c.append("            }") # End inner loop
            
            if idx < len(self.layer_meta) - 1:
                # Intermediate layers receive DRAIN/ReLU processing mapping back to Hidden array H
                c.append(f"            npu_load_bias(&bias_l{idx+1}[j * 8]);")
                c.append(f"            npu_drain_to_ddr(0x900000);")
                c.append("            for(int r=0; r<8; r++) { for(int c=0; c<8; c++) { H[r][j*8+c] = l1_drain_buf[r*8+(7-c)]; } }")
            else:
                # Terminal layer executes flat memory extraction for Classification CPU Head
                c.append("            int32_t host_z_buf[64] = {0};")
                c.append(f"            npu_extract_32bit_ocm(host_z_buf, &bias_l{idx+1}[j * 8]);")
                c.append("            for(int r=0; r<8; r++) { for(int c=0; c<8; c++) { ((int32_t*)virt_ddr_base)[0x910000/4 + (r*16) + (j*8+c)] = host_z_buf[r*8+c]; } }")

            c.append("        }") # End outer loop
            c.append("")
        
        c.append("        // Standard Evaluation (CPU ArgMax)")
        c.append("        int32_t* Y_final = (int32_t*)(virt_ddr_base + 0x910000);")
        c.append("        for (int r = 0; r < 8; r++) {")
        c.append("            int best_class = 0; int32_t max_val = Y_final[r*16 + 0];")
        c.append("            for (int k = 1; k < 10; k++) {")
        c.append("                if (Y_final[r*16 + k] > max_val) { max_val = Y_final[r*16 + k]; best_class = k; }")
        c.append("            }")
        c.append("            if (best_class == labels[b * 8 + r]) correct_predictions++;")
        c.append("        }")
        c.append("    }")
        
        c.append("")
        c.append("    gettimeofday(&tv, NULL);")
        c.append("    double end_time = (double)tv.tv_sec * 1000000.0 + (double)tv.tv_usec;")
        c.append("    *time_ms = (end_time - start_time) / 1000.0;")
        c.append("    *accuracy = (double)correct_predictions / (num_batches * 8) * 100.0;")
        c.append("}")
        c.append("")
        
        # Add pure standalone C Main wrapper
        c.append("int main(int argc, char **argv) {")
        c.append("    int num_test_batches = 125;")
        c.append("    if (argc > 1) { num_test_batches = atoi(argv[1]) / 8; }")
        c.append("    printf(\"=== Auto-Generated EmitC NPU Benchmark ===\\n\");")
        c.append("    if (npu_init() < 0) return -1;")
        c.append("    printf(\"\\nLoading Binaries...\\n\");")
        c.append("    npu_load_binary_file(\"inputs.bin\", virt_ddr_base + 0x000000, 8000000);")
        
        for idx, layer in enumerate(self.layer_meta):
            c.append(f"    npu_load_binary_file(\"weights_l{idx+1}.bin\", virt_ddr_base + 0x{layer['weight_addr']:06X}, 200000);")
            c.append(f"    npu_load_binary_file(\"bias_l{idx+1}.bin\", bias_l{idx+1}, 256);")
            
        c.append("    npu_load_binary_file(\"labels.bin\", labels, 40000);")
        c.append("    double time_ms, acc;")
        c.append("    npu_auto_inference(num_test_batches, &time_ms, &acc);")
        c.append("    printf(\"    EmitC Accuracy : %.2f%%\\n\", acc);")
        c.append("    printf(\"    EmitC Time     : %.2f ms (%.3f ms/img)\\n\", time_ms, time_ms / (num_test_batches * 8));")
        c.append("    npu_close();")
        c.append("    return 0;")
        c.append("}")
        c.append("")
        
        # Write File
        with open(self.out_c_file, "w") as f:
            f.write("\n".join(c))
        print(f"[EmitC] Generated NPU Standalone Execution Runtime: {self.out_c_file}")

